services:
  - type: web
    name: joshika-portfolio-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/projects
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: PORT
        value: 5000
